version: "3.4"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    restart: "no"
    ports:
      - "80:80"
  dispatcher:
    restart: "no"
  frontend:
    # image: # specify the same image than the one in docker-compose, but without the "-fastboot" suffix here for a fastboot-less local setup
    restart: "no"
  database:
    restart: "no"
  delta-notifier:
    restart: "no"
  triplestore:
    restart: "no"
  migrations:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  file:
    restart: "no"
  uri-info:
    restart: "no"
  resource-labels-cache:
    restart: "no"
  resource-labels:
    restart: "no"
  publication-consumer:
    restart: "no"
  themis-same-as:
    restart: "no"
  dcat-dataset-publication:
    restart: "no"
  mail-delivery:
    restart: "no"
