PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>

INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://public-api/distributions/dd8abdfa-fe49-11ea-adc1-0242ac120002> a dcat:Distribution ;
            mu:uuid "dd8abdfa-fe49-11ea-adc1-0242ac120002" ;
            dct:title "Mijn eerste Distribution" ;
            dct:description "Mijn eerste Distribution Description" ;
            dct:accessURL "http://redpencil.io" .

        <http://public-api/distributions/3e357588-ff16-11ea-adc1-0242ac120002> a dcat:Distribution ;
            mu:uuid "3e357588-ff16-11ea-adc1-0242ac120002" ;
            dct:title "Mijn tweede Distribution" ;
            dct:description "Mijn tweede Distribution Description" ;
            dct:accessURL "http://redpencil.io" .
    }
}
