PREFIX dct: <http://purl.org/dc/terms/>

INSERT DATA {
    GRAPH <http://mu.semte.ch/graphs/public> {
        <http://themis.vlaanderen.be/id/distribution/ae76dd1f-745e-4b19-9811-6c0823a523ba> dct:subject <http://themis.vlaanderen.be/id/resource/5c17fb60-c870-11eb-8401-0daf85bdaac4> .
    }
}