steps:
  generate-dataset-script-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER%%-vlaanderen}/generate-dataset-script"
      dockerfile: scripts/generate-dataset/Dockerfile
      context: scripts/generate-dataset
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  generate-mandatees-script-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER%%-vlaanderen}/generate-mandatees-script"
      dockerfile: scripts/generate-mandatees/Dockerfile
      context: scripts/generate-mandatees
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [master]
